version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgresTAM
    networks:
      - my-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-secret-pw

#  redis:
#    image: redis
#    container_name: redis
#    networks:
#      - my-network
#    ports:
#      - "6379:6379"
#    command: --bind 0.0.0.0

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmqTAM
    networks:
      - my-network
    ports:
      - "5672:5672"

  review-microservices:
    build:
      context: ./ReviewMicroservices
      dockerfile: Dockerfile
    container_name: tam-review-app
    networks:
      - my-network
    ports:
      - "5003:8000"
    environment:
      DB_HOST: postgres
      DB_NAME: db
      DB_USERNAME: postgres
      DB_PASSWORD: my-secret-pw
#      REDIS_HOST: redis
#      REDIS_DATABASE: "0"
      #RABBITMQ_HOST: rabbitmq
    depends_on:
      - postgres
#      - redis
     # - rabbitmq

networks:
  my-network:
    driver: bridge
