global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'book_microservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['book-microservices:8000']
  - job_name: 'order_microservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'order-microservice-api:8000' ]
  - job_name: 'review_microservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'review-microservices:8000' ]